## in R, variable assignments are traditionally done using '<-' but now can also be done using '=' as most languages allow as convention

# <span style="color:orange"> LISTS </span>

In [1]:
l1 <- list("a", 1, TRUE, pi=3.14)
print(l1)

[[1]]
[1] "a"

[[2]]
[1] 1

[[3]]
[1] TRUE

$pi
[1] 3.14



In [2]:
l1 = list("a", 1, TRUE, 3.14)
print(l1)

[[1]]
[1] "a"

[[2]]
[1] 1

[[3]]
[1] TRUE

[[4]]
[1] 3.14



In [3]:
# needs the 'double brackets' to dereference
print( l1[[1]] )
print( l1[[4]] )

[1] "a"
[1] 3.14


In [4]:
#modify an entry via double bracket index
l1[[2]] <- 2
print( l1 )

[[1]]
[1] "a"

[[2]]
[1] 2

[[3]]
[1] TRUE

[[4]]
[1] 3.14



In [5]:
l1[[5]] = "new item"
print( l1 )

[[1]]
[1] "a"

[[2]]
[1] 2

[[3]]
[1] TRUE

[[4]]
[1] 3.14

[[5]]
[1] "new item"



In [6]:
# removing an element
l1[[2]] <- NULL
print(l1)

[[1]]
[1] "a"

[[2]]
[1] TRUE

[[3]]
[1] 3.14

[[4]]
[1] "new item"



In [7]:
length( l1 )

[1] 4

In [8]:
#print with a message (places a default white space after each string)
print( paste("Length of list:", length( l1 ) ) )

[1] "Length of list: 4"


In [9]:
cat( paste("Length of list:", length( l1 ) ) )

Length of list: 4

In [11]:
str( l1 )

List of 4
 $ : chr "a"
 $ : logi TRUE
 $ : num 3.14
 $ : chr "new item"


In [12]:
names( l1 )

NULL

In [ ]:
# add names, but only 4 names for the 5 elements
n ames( l1 )<- c("firstElement", "El with Spaces", "3", "cool_name")

In [14]:
names( l1 )

[1] "firstElement"   "El with Spaces" "3"              "cool_name"

In [15]:
l1['3']

$`3`
[1] 3.14

In [16]:
l1['El with Spaces']

$`El with Spaces`
[1] TRUE

In [17]:
l1$firstElement

[1] "a"

In [18]:
l1$'firstElement'

[1] "a"

In [19]:
#won't work
l1$3

ERROR: Error in parse(text = input): <text>:2:4: unexpected numeric constant
1: #won't work
2: l1$3
      ^


In [20]:
#works
l1$'3'

[1] 3.14

In [21]:
l1$"El with Spaces"

[1] TRUE

In [22]:
names(l1)[5]

[1] NA

In [23]:
names(l1)[5] = "fifth Element"

ERROR: Error in names(l1)[5] = "fifth Element": 'names' attribute [5] must be the same length as the vector [4]


In [24]:
names(l1)[5]

[1] NA

In [25]:
names( l1 )

[1] "firstElement"   "El with Spaces" "3"              "cool_name"

In [10]:
for( i in seq_along( l1 ) ) {
  print( paste( "Length of element", names( l1 )[i], ":", length( l1[[i]] ) ) )
}

[1] "Length of element  : 1"
[1] "Length of element  : 1"
[1] "Length of element  : 1"
[1] "Length of element  : 1"


In [27]:
#two separate lists
list1 = list(fruit = "apple", count = 10)
list2 = list(price = 2.5, category = "produce")

#combine the lists
combined_list = c(list1, list2)
print(combined_list)

$fruit
[1] "apple"

$count
[1] 10

$price
[1] 2.5

$category
[1] "produce"



In [28]:
#recursive lists!
dir = list(
  folder1 = list(file1 = "document.txt", file2 = "photo.jpg"),
  folder2 = list(
    subfolder = list(file3 = "presentation.pptx")
  )
)

#access a deeply nested
nested_file = dir$folder2$subfolder$file3
print(nested_file)

[1] "presentation.pptx"


In [41]:
#make a nested list and then flatten it!
nested_list = list(
  a = list(1, 2),
  b = list(3, list(4, 5,6),
  c = list('a','bb','ccc'),
  d = list(c(11,22,33,44,55)))
)

#our function to flatten a list
flatten_list = function(x) {
  unlist(x, recursive = TRUE)
}

#flatten the list
flat_list = flatten_list(nested_list)
cat(flat_list) 

1 2 3 4 5 6 a bb ccc 11 22 33 44 55

In [11]:
#a list holding functions! (fns are variables too)
math_functions = list(
  my_square = function(x) x^2,
  my_cube = function(x) x^3,
  my_sqrt = sqrt
)

#get a function from the list and use it
result = math_functions$my_square(4)
print(result)  
result = math_functions$my_cube(3)
print(result)  

[1] 16
[1] 27


In [12]:
name_list = list(alex = 3, bob = 5, chris = 7)
#get multiple elements
selected_names = fruit_list[c("alex", "chris")]
print(selected_names)
cat("\n--------------\n")
selected_names = fruit_list[c("alex", "derek")]
print(selected_names)

ERROR: Error: object 'fruit_list' not found


## <span style="color:orange"> Questions </span> 

1. Create a list named 'cool_list' containing a numeric vector, a character vector, and a logical vector
2. add a new element (char/string) to this list
3. remove the second element
4. add another element that is a list itself with a vector of numbers and vector of chars
5. print the vector of chars in the sublist

# <span style="color:orange"> More List Questions </span>
- nested list:
```r
nested_list = list(
  fruits = list(apple = 3, banana = 5, cherry = 7),
  vegetables = list(carrot = 2, broccoli = 4)
)
```

get the value of the 'broccoli' from the 'vegetables' list

- veg_list = list(fruits = list(apple = 3, banana = 5), vegetables = list(carrot = 2, broccoli = 4))

add a new element to the fruits sublist with grape = 6, then change the value of carrot in the vegetables sublist to 3

- modify this code to get the sums of each list element

```r
number_list = list(a = c(1, 2, 3), b = c(4, 5, 6), c = c(7, 8, 9))
sums = list()

for (name in names(number_list)) {
    ???
}
print(sums)
```

In [ ]:
v1 = c(1,2,3)
v2 = c(3,4,"v")
m1 = matrix(v1)
m2 = matrix(v2)
m1

[1] TRUE

# <span style="color:orange"> Matrices </span>

In [14]:
mat1 = matrix(1:6, nrow = 3, ncol = 2)
print(mat1)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [15]:
vec1 = 1:3
vec2 = 4:6

In [16]:
is.vector(vec1)

[1] TRUE

In [17]:
is.matrix(vec1)

[1] FALSE

In [18]:
mat2 = cbind(vec1, vec2)
print( mat2 )

     vec1 vec2
[1,]    1    4
[2,]    2    5
[3,]    3    6


In [37]:
is.vector(mat2)

[1] FALSE

In [19]:
is.matrix(mat2)

[1] TRUE

In [20]:
is.data.frame(mat2)

[1] FALSE

In [39]:
#beware
cat( mat1 )
cat( mat2 )

1 2 3 4 5 61 2 3 4 5 6

In [21]:
mat3 = rbind( vec1 , vec2 )
print( mat3 )

     [,1] [,2] [,3]
vec1    1    2    3
vec2    4    5    6


In [22]:
dim(mat3)

[1] 2 3

In [23]:
mat3[1,1] = -1
mat3[2,2] = mat3[1,1]
mat3[1,3] = 10 * mat3[1,3]
print( mat3 )

     [,1] [,2] [,3]
vec1   -1    2   30
vec2    4   -1    6


In [25]:
#change a column
mat3[ , 3 ] = c( -10 , -20 )
print( mat3 )

     [,1] [,2] [,3]
vec1   -1    2  -10
vec2    4   -1  -20


In [44]:
#change a row
mat3[ 1 , ] = 10 * mat3[ 1 , ]
print( mat3 )

     [,1] [,2] [,3]
vec1  -10   20 -100
vec2    4   -1  -20


In [45]:
# add a column
mat3 = cbind( mat3 , c( 123 , 321 ) )
print( mat3 )

     [,1] [,2] [,3] [,4]
vec1  -10   20 -100  123
vec2    4   -1  -20  321


In [46]:
# add a row
mat3 = rbind( mat3 , 1:ncol(mat3) )
print( mat3 )

     [,1] [,2] [,3] [,4]
vec1  -10   20 -100  123
vec2    4   -1  -20  321
        1    2    3    4


In [47]:
rownames(mat3)

[1] "vec1" "vec2" ""

In [48]:
rownames(mat3)[3] = "vec3"

In [49]:
rownames(mat3)

[1] "vec1" "vec2" "vec3"

In [50]:
#remove col 4
mat3 = mat3[ , -4 ]
print( mat3 )

     [,1] [,2] [,3]
vec1  -10   20 -100
vec2    4   -1  -20
vec3    1    2    3


In [51]:
#remove col 4
mat3 = mat3[ , -4 ]
print( mat3 )

     [,1] [,2] [,3]
vec1  -10   20 -100
vec2    4   -1  -20
vec3    1    2    3


In [52]:
#remove a row
mat3 = mat3[ -2 , ]
print( mat3 )

     [,1] [,2] [,3]
vec1  -10   20 -100
vec3    1    2    3


In [53]:
#matrix within matrix
print( mat1[ 1:2, 1:2 ] ) 

     [,1] [,2]
[1,]    1    4
[2,]    2    5


In [54]:
mat1

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

In [55]:
is.matrix( mat1[ c(1,2), c(1,3) ] ) 

ERROR: Error in mat1[c(1, 2), c(1, 3)]: subscript out of bounds


In [56]:
submat = mat1[ 1:2, 1:2 ]
print( submat )

     [,1] [,2]
[1,]    1    4
[2,]    2    5


In [57]:
rownames( submat ) = c( "Row1" , "Row2" )
colnames( submat ) = c( "Col1" , "Col2" )

In [58]:
print( submat )

     Col1 Col2
Row1    1    4
Row2    2    5


In [59]:
print( dim(submat) )

[1] 2 2


In [60]:
print( nrow( submat ) )

[1] 2


In [61]:
print( ncol( submat ) )

[1] 2


In [62]:
#transpose
print( t(submat) )

     Row1 Row2
Col1    1    2
Col2    4    5


In [63]:
# diagonal elements
print( diag( submat ) )

[1] 1 5


In [64]:
newmat = submat + submat
print( newmat )

     Col1 Col2
Row1    2    8
Row2    4   10


In [65]:
#elementwise multiplication
newmat = submat * submat
print( newmat )

     Col1 Col2
Row1    1   16
Row2    4   25


In [66]:
# Matrix multiplication
newmat = submat %*% submat
print( newmat )

     Col1 Col2
Row1    9   24
Row2   12   33


In [67]:
as.matrix(c(1,2,3,4,5,6,7,8))

[,1]
[1,] 1   
[2,] 2   
[3,] 3   
[4,] 4   
[5,] 5   
[6,] 6   
[7,] 7   
[8,] 8

In [68]:
matrix( c(1,2,3,4,5,6,7,8) , nrow= 2 , ncol= 4 )

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [69]:
submat

Col1 Col2
Row1 1    4   
Row2 2    5

In [70]:
# Reshaping a matrix to 4x1
mat_reshaped = matrix(submat, nrow = 4, ncol = 1)
print(mat_reshaped)

     [,1]
[1,]    1
[2,]    2
[3,]    4
[4,]    5


In [71]:
# Reshaping a matrix to 1x4
mat_reshaped = matrix(submat, nrow = 1, ncol = 4)
print(mat_reshaped)

     [,1] [,2] [,3] [,4]
[1,]    1    2    4    5


In [72]:
mat_subset = submat[submat > 2]
print(mat_subset)

[1] 4 5


In [73]:
print(submat > 2)

      Col1 Col2
Row1 FALSE TRUE
Row2 FALSE TRUE


In [74]:
#stack matrices
mat_rowbind <- rbind(submat, submat)
print(mat_rowbind)

     Col1 Col2
Row1    1    4
Row2    2    5
Row1    1    4
Row2    2    5


In [75]:
#stack matrices horizontally
mat_colbind = cbind(submat, submat)
print( mat_colbind )

     Col1 Col2 Col1 Col2
Row1    1    4    1    4
Row2    2    5    2    5


In [76]:
#matrix inversion
solve( submat )

Row1       Row2      
Col1 -1.6666667  1.3333333
Col2  0.6666667 -0.3333333

In [77]:
matrix1 = matrix(1:9, nrow = 3, byrow = TRUE)
print(matrix1)
element = matrix1[2, 3]
print(element)
matrix1[2, 3] = 10
print(matrix1)
row_sums = rowSums(matrix1)
col_means = colMeans(matrix1)
print(row_sums)
print(col_means)

     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5    6
[3,]    7    8    9
[1] 6
     [,1] [,2] [,3]
[1,]    1    2    3
[2,]    4    5   10
[3,]    7    8    9
[1]  6 19 24
[1] 4.000000 5.000000 7.333333


In [78]:
transposed_matrix = t(matrix1)
print(transposed_matrix)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3   10    9


In [79]:
matrix2 = matrix(1:9, nrow = 3)
matrix3 = matrix(9:1, nrow = 3)
matrix_sum = matrix2 + matrix3
matrix_diff = matrix2 - matrix3
print(matrix_sum)
print(matrix_diff)

     [,1] [,2] [,3]
[1,]   10   10   10
[2,]   10   10   10
[3,]   10   10   10
     [,1] [,2] [,3]
[1,]   -8   -2    4
[2,]   -6    0    6
[3,]   -4    2    8


In [80]:
matrix2 = matrix(1:9, nrow = 3)
matrix3 = matrix(9:1, nrow = 3)
#element-wise multiplication
matrix_product = matrix2 * matrix3
print(matrix_product)

     [,1] [,2] [,3]
[1,]    9   24   21
[2,]   16   25   16
[3,]   21   24    9


In [81]:
#matrix multiplication
matrix_mult = matrix2 %*% matrix3
print(matrix_mult)

     [,1] [,2] [,3]
[1,]   90   54   18
[2,]  114   69   24
[3,]  138   84   30


In [82]:
matrix1 = matrix(1:9, nrow = 3)
matrix2 = matrix(9:1, nrow = 3)
#vertical stack
row_combined = rbind(matrix1, matrix2)
print(row_combined)
#horizontal concatenation
col_combined = cbind(matrix1, matrix2)
print(col_combined)

     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9
[4,]    9    6    3
[5,]    8    5    2
[6,]    7    4    1
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    1    4    7    9    6    3
[2,]    2    5    8    8    5    2
[3,]    3    6    9    7    4    1


In [83]:
#make a vector into a matrix
vec = 1:12
reshaped_matrix = matrix(vec, nrow = 3, ncol = 4)
print(reshaped_matrix)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [84]:
char_vec = c("apple", "banana", "cherry", "date", "elderberry", "fig")

#char vector into a 2x3 matrix
char_matrix = matrix(char_vec, nrow = 2, ncol = 3)
print(char_matrix)

     [,1]     [,2]     [,3]        
[1,] "apple"  "cherry" "elderberry"
[2,] "banana" "date"   "fig"       


In [85]:
#create a list with mixed types
my_list = list(1, "apple", TRUE, 2.5)
#convert the list into a matrix (will coerce to character)
list_matrix = matrix(unlist(my_list), nrow = 2, ncol = 2)
print(list_matrix)

     [,1]    [,2]  
[1,] "1"     "TRUE"
[2,] "apple" "2.5" 


In [86]:
numeric_matrix = matrix(11:19, nrow = 3, byrow = TRUE)
#convert the matrix to a list
matrix_as_list = as.list(numeric_matrix)
print(matrix_as_list)

[[1]]
[1] 11

[[2]]
[1] 14

[[3]]
[1] 17

[[4]]
[1] 12

[[5]]
[1] 15

[[6]]
[1] 18

[[7]]
[1] 13

[[8]]
[1] 16

[[9]]
[1] 19



In [87]:
numeric_matrix = matrix(11:19, nrow = 3, byrow = TRUE)
matrix_as_vector = as.vector(numeric_matrix)
print(matrix_as_vector)
reshaped_matrix = matrix(matrix_as_vector, nrow = 3, byrow = TRUE)
print(reshaped_matrix)

[1] 11 14 17 12 15 18 13 16 19
     [,1] [,2] [,3]
[1,]   11   14   17
[2,]   12   15   18
[3,]   13   16   19


In [88]:
numeric_matrix = matrix(11:19, nrow = 3, byrow = TRUE)
row_vector = numeric_matrix[1, ]
print(row_vector) 
col_vector = numeric_matrix[, 2]
print(col_vector)
row_list = as.list(numeric_matrix[1, ])
print(row_list)

[1] 11 12 13
[1] 12 15 18
[[1]]
[1] 11

[[2]]
[1] 12

[[3]]
[1] 13



## QUESTIONS
- Create a 4x3 matrix with numbers from 1 to 12, filled column-wise. Then, replace the value in the 2nd row and 3rd column with `99`.
- Create a 3x3 matrix in R with the numbers 1 through 9 filled column-wise. 
- Create a 4x3 matrix filled with the sequence of numbers from 10 to 21 (inclusive). What does the resulting matrix look like when filled column-wise?

 [,1] [,2] [,3]

[1,] 10 14 18 [2,] 11 15 19 [3,] 12 16 20 [4,] 13 17 21
- from the previous result calculate the sum of each row. What are the row sums?

[1] 42 45 48 51
- From the matrix previous result, extract all elements greater than 15. What are the resulting values?
[1] 16 17 18 19 20 21
- Take the previous matrix transpose it. What does the resulting transposed matrix look like?
 [,1] [,2] [,3] [,4]  ...
[1,] 10 11 12 13 [2,] 14 15 16 17 [3,] 18 19 20 21




-Create a 3x3 matrix with the numbers 1 through 9, filled by rows. Reverse the order of the columns. What does the resulting matrix look like?

(result):
 [,1] [,2] [,3]

[1,] 3 2 1 [2,] 6 5 4 [3,] 9 8 7

Create a 4x4 matrix filled with the sequence 1 to 16, filled column-wise. Extract the diagonal elements. What are the diagonal values?

(result): [1] 1 6 11 16

- Given the two matrices below:
Matrix X:

 [,1] [,2]

[1,] 1 2 [2,] 3 4

Matrix Y:

 [,1] [,2]

[1,] 5 6 [2,] 7 8

Perform element-wise multiplication. What is the result?

result:

 [,1] [,2]

[1,] 5 12 [2,] 21 32